from __future__ import annotations

import os
import subprocess
from pathlib import Path

from .models import Route, ValidationError


def render(routes: dict[str, Route], cert_root: Path) -> str:
    enabled = [route for route in routes.values() if route.enabled]
    _validate_unique_domains(enabled)
    sections = ["# Generated by vps-gateway. Do not edit.\n"]
    for route in sorted(enabled, key=lambda item: item.id):
        if route.tls:
            _validate_certificates(route, cert_root)
        sections.append(_render_route(route, cert_root))
    return "\n".join(sections)


def install_candidate(content: str, target: Path, nginx_config: Path, reload_nginx: bool) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    candidate = target.with_suffix(".candidate")
    backup = target.with_suffix(".previous")
    _atomic_write(candidate, content)
    had_target = target.exists()
    if had_target:
        os.replace(target, backup)
    os.replace(candidate, target)
    try:
        subprocess.run(
            ["nginx", "-t", "-e", "/dev/stderr", "-c", str(nginx_config)],
            check=True,
            capture_output=True,
            text=True,
        )
        if reload_nginx:
            subprocess.run(
                ["nginx", "-s", "reload", "-e", "/dev/stderr", "-c", str(nginx_config)],
                check=True,
                capture_output=True,
                text=True,
            )
    except (OSError, subprocess.CalledProcessError) as error:
        if had_target:
            os.replace(backup, target)
        else:
            target.unlink(missing_ok=True)
        detail = error.stderr.strip() if isinstance(error, subprocess.CalledProcessError) and error.stderr else str(error)
        raise RuntimeError(f"NGINX rejected the route configuration: {detail}") from error
    backup.unlink(missing_ok=True)


def _render_route(route: Route, cert_root: Path) -> str:
    names = " ".join(route.domains)
    proxy = _proxy_block(route)
    http_action = "return 308 https://$host$request_uri;" if route.tls else proxy
    sections = [
        f"# route: {route.id}",
        "server {",
        "    listen 8080;",
        f"    server_name {names};",
        "",
        "    location ^~ /.well-known/acme-challenge/ {",
        "        root /var/www/acme;",
        "        default_type text/plain;",
        "    }",
        "",
        "    location / {",
        _indent(http_action, 8),
        "    }",
        "}",
    ]
    if route.tls:
        primary = route.domains[0]
        cert_dir = cert_root / primary
        sections.extend(
            [
                "",
                "server {",
                "    listen 8443 ssl;",
                f"    server_name {names};",
                f"    ssl_certificate {cert_dir / 'fullchain.pem'};",
                f"    ssl_certificate_key {cert_dir / 'privkey.pem'};",
                "    ssl_protocols TLSv1.2 TLSv1.3;",
                "    ssl_session_cache shared:GatewayTLS:10m;",
                "    ssl_session_timeout 1d;",
                "    add_header Strict-Transport-Security \"max-age=31536000\" always;",
                "",
                "    location / {",
                _indent(proxy, 8),
                "    }",
                "}",
            ]
        )
    return "\n".join(sections) + "\n"


def _proxy_block(route: Route) -> str:
    websocket = (
        "proxy_http_version 1.1;\n"
        "proxy_set_header Upgrade $http_upgrade;\n"
        "proxy_set_header Connection $gateway_connection;\n"
        if route.websocket
        else "proxy_http_version 1.1;\nproxy_set_header Connection \"\";\n"
    )
    return (
        f"set $gateway_target \"{route.upstream}\";\n"
        f"client_max_body_size {route.max_body_mb}m;\n"
        f"{websocket}"
        "proxy_set_header Host $host;\n"
        "proxy_set_header X-Real-IP $remote_addr;\n"
        "proxy_set_header X-Forwarded-For $remote_addr;\n"
        "proxy_set_header X-Forwarded-Host $host;\n"
        "proxy_set_header X-Forwarded-Proto $scheme;\n"
        "proxy_set_header X-Forwarded-Port $gateway_forwarded_port;\n"
        "proxy_connect_timeout 5s;\n"
        "proxy_read_timeout 60s;\n"
        "proxy_send_timeout 60s;\n"
        "proxy_pass $gateway_target;"
    )


def _validate_unique_domains(routes: list[Route]) -> None:
    owners: dict[str, str] = {}
    for route in routes:
        for domain in route.domains:
            if domain in owners:
                raise ValidationError(f"domain {domain} is already owned by route {owners[domain]}")
            owners[domain] = route.id


def _validate_certificates(route: Route, cert_root: Path) -> None:
    cert_dir = cert_root / route.domains[0]
    for filename in ("fullchain.pem", "privkey.pem"):
        path = cert_dir / filename
        if not path.is_file():
            raise ValidationError(f"TLS certificate file does not exist: {path}")
    certificate = cert_dir / "fullchain.pem"
    _check_certificate(["-checkend", "0"], certificate, "is expired")
    for domain in route.domains:
        _check_certificate(["-checkhost", domain], certificate, f"does not cover {domain}")


def _check_certificate(arguments: list[str], certificate: Path, failure: str) -> None:
    try:
        subprocess.run(
            ["openssl", "x509", *arguments, "-noout", "-in", str(certificate)],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError) as error:
        detail = error.stderr.strip() if isinstance(error, subprocess.CalledProcessError) and error.stderr else str(error)
        raise ValidationError(f"TLS certificate {failure}: {detail}") from error


def _atomic_write(path: Path, content: str) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    with temporary.open("w", encoding="utf-8") as handle:
        handle.write(content)
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(temporary, path)


def _indent(value: str, spaces: int) -> str:
    prefix = " " * spaces
    return "\n".join(prefix + line for line in value.splitlines())
